### ISSUE TITLE
gcc --version must be 4.9?

### ISSUE THREAD

**Issue by hyaihjq** [simonmeister/UnFlow#1]
gcc --version must be 4.9?

**Comment by hyaihjq** [comment]
when run python run.py --ex my_experiment, have a error:
subprocess.CalledProcessError: Command 'g++-4.8 -std=c++11 -shared -o backward_warp_op.so backward_warp_op.cu.o backward_warp_op.cc -I /home/hongyang/anaconda3/lib/python3.5/site-packages/tensorflow/include -fPIC -lcudart -D GOOGLE_CUDA=1 -L /opt/cuda/lib64' returned non-zero exit status 127

**Comment by simonmeister** [comment]
I didn't try it out, but it should probably also work with 4.8. In the tensorflow docs, they say "The recommended minimum gcc version is 4.8.3.". Can you try to run the command manually and see what it outputs (the full command you posted in subprocess.CalledProcessError: Command '...')?

**Comment by hyaihjq** [comment]
my tensorflow install with anaconda3 , i modify config.ini "g++=g++-4.9" to"g++=g++",now i can run the command "python run.py --ex my_experiment",thank you.

**Comment by simonmeister** [comment]
Ok, great!
