### ISSUE TITLE
How to test your pretrained model with different input image?

### ISSUE THREAD

**Issue by yuanliangzhe** [simonmeister/UnFlow#11]

**Comment by yuanliangzhe** [comment]
Hi, 
Is there any way that I can use your pretrained model, say CSS_ft, to run with other inputs with different image size?
Thanks!

**Comment by yuanliangzhe** [comment]
Ahh I got it. 
One more following question, if my input image size is very different from the images you used to train the model, would the performance be effected by resizing input?

**Comment by simonmeister** [comment]
I am not sure on that, you need to try it out. In general, resizing should be fine. If you want to resize the flow output to the original image size again, you need to keep in mind to scale the resulting flow appropriately (proportional to the change of scale in each direction, see https://github.com/simonmeister/UnFlow/blob/master/src/e2eflow/core/input.py#L28).

**Comment by sahityamantravadi** [comment]
@yuanliangzhe How did you run the pretrained Unflow model on a new set of images?

Thanks!

**Comment by yuanliangzhe** [comment]
Hi @sahityamantravadi , we hacked into the code and replace the dataloader with our own. One quickest way to test with your own images would be naming your images as the dataset naming format, say KITTI's, and place them into the corresponding folders.

Good luck!
