### ISSUE TITLE
Performance on Middleburry and Sintel

### ISSUE THREAD

**Issue by Yuliang-Zou** [simonmeister/UnFlow#14]
Hi, can you tell me how did you set the image size for Middleburry and Sintel evaluation? Since I notice that input size matters a lot.

**Comment by simonmeister** [comment]
Hi! From https://github.com/simonmeister/UnFlow/blob/master/src/eval_gui.py#L28:

- middlebury: height = 512, width = 640
- sintel: height = 512, width = 1024

**Comment by Yuliang-Zou** [comment]
Thanks a lot!
