### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by wpfhtl** [simonmeister/UnFlow#18]
The CPU memory goes larger continuously as training until it explode.

**Comment by simonmeister** [comment]
Hi, are you training on CPU or GPU? How long did you train? Can you give more details of your environment (os, tensorflow version, ...). I trained for multiple days on different machines and it didn't crash due to a leak.

**Comment by wpfhtl** [comment]
Training with GPU, GTX Titan 1080. Ubuntu 16.04, tensorflow 1.2. During training, the GPU memory didn't explode, but the CPU memory increase continuously until 100%

**Comment by wpfhtl** [comment]
I noticed that if I set the " tf.app.flags.DEFINE_boolean('debug', True)", the memory consumption will increase fast.

**Comment by simonmeister** [comment]
This flag enables recording and writing images to tensorboard, but i don't really know why it should cause a memory leak. On what timescale does the memory increase?

**Comment by wpfhtl** [comment]
50000 iteration, it will consume near 30G memory

**Comment by simonmeister** [comment]
Is the 30GB with or without the debug Flag? The flag isn't meant to be used during full training. Could you maybe share your complete config.ini file with me?

**Comment by wpfhtl** [comment]
The 30GB with the debug Flag, this is the config.ini.
[config.ini.txt](https://github.com/simonmeister/UnFlow/files/1901150/config.ini.txt)

**Comment by simonmeister** [comment]
As I was not able to reproduce, I am closing this for now.
