### ISSUE TITLE
i have "pip install rarfile",but i have a error rarfile.rarcannotexec("unrar not installed?")

### ISSUE THREAD

**Issue by hyaihjq** [simonmeister/UnFlow#2]
![screenshot from 2017-12-18 15_07_55](https://user-images.githubusercontent.com/27874026/34093954-0d99a922-e406-11e7-9acd-c9b8ffd68164.png)

**Comment by simonmeister** [comment]
You need to install the unrar command line tool: sudo apt-get install unrar (on ubuntu).
