### ISSUE TITLE
regarding image normalization

### ISSUE THREAD

**Issue by stalin18** [simonmeister/UnFlow#20]
Hi, I see that you perform mean normalization with:

mean = [104.920005, 110.1753, 114.785955]
stddev = 1 / 0.0039216

Are these values from ImageNet dataset? I'm curious to know if performing normalization considerably affected (improved) your results? I believe none of the papers (your's included) explicitly mention about input image normalization for optical flow. Thanks!

**Comment by simonmeister** [comment]
The stddev is about 255, so it's simply re-scaling the range to be approximately contained in [-1, 1]. I believe for the mean values, just using 255/2 should work equally well, but i only tried training with this normalization. I used the mean from the code at "http://scs.ryerson.ca/~jjyu/projects/unsupervised/optical/flow/machine/learning/2016/08/30/Unsup-flow.html" and i think it's the KITTI mean.

**Comment by wpfhtl** [comment]
what about the mean of sintel and synthia. It looks you didn't use mean in synthia, but use the same mean in sintel with kitti.

**Comment by simonmeister** [comment]
The same mean is used everywhere.
