### ISSUE TITLE
error with tensorflow

### ISSUE THREAD

**Issue by DongJT1996** [simonmeister/UnFlow#24]
Hi,
I try to run the code: python run.py --ex my_experiment
but there are two errors, as shown following:
and i use tensorlow1.7.0, and my os is ubuntu16.04

![image](https://user-images.githubusercontent.com/25705996/39095476-99bb30c2-4673-11e8-873a-1f9d89dd10e9.png)

**Comment by clauslang** [comment]
You need to install the cuda toolkit, so that the _nvcc_ command is available:

`sudo apt install nvidia-cuda-toolkit`

See #23.

**Comment by simonmeister** [comment]
I updated the README to emphasize that CUDA needs to be installed. Thanks @clauslang!
