### ISSUE TITLE
Some confuse about the function of "create_border_mask"

### ISSUE THREAD

**Issue by EnQing626** [simonmeister/UnFlow#25]
Hello Simon,
Thanks for your fantastic work and code!
I am new to the task of video and I have a question about the definition of "border_mask " in losses.py:

Why do we need to use these masks when computing CharbonnierLoss?

Thanks so much in advance

**Comment by simonmeister** [comment]
Hi,

in the border region, the flow at many positions will point outside the image and thus the brightness constancy assumption will not hold. Empirically, we found it difficult to train without getting artifacts in the border region without this constant border mask (which simply disables the brightness constancy loss at these regions).

**Comment by EnQing626** [comment]
I have understood this definition from your answer. Thank you for your prompt reply~
