### ISSUE TITLE
If no ground truth is available, can self.eval(1) in run() in train.py be safely outcommented?

### ISSUE THREAD

**Issue by Santana18** [simonmeister/UnFlow#26]
https://github.com/simonmeister/UnFlow/edit/master/src/e2eflow/core/train.py line 142: self.eval(1)

Or is there a simple way to modify the eval() function, if no ground truth is available? Or is an important step for training/finetuning disabled if eval() does not get called?

Thank you!

**Comment by simonmeister** [comment]
Sure, you can comment it out if you don't want to do evaluation regularly during training.
