### ISSUE TITLE
Invalid argument: Input height and width must be divisible by scale

### ISSUE THREAD

**Issue by Blcony** [simonmeister/UnFlow#28]
Hi Simon!
Thanks for your work and code, it's very helpful to me!
But I have some questions now, please give me some advices.
I want to train your network on my own datasets, but the size of my data is different from kitti or synthia. So I have to reset the height and weight parameter in config.ini. 
The question is when I set height and weight to 1000( the size of my data is 4000*4000) and try to run the code, I'll get informations shown below:

tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Input height and width must be divisible by scale
 [[Node: loss3/Downsample = Downsample[[scale=2, _device="/job:localhost/replica:0/task:0/gpu:0"](loss2/Downsample)]]

I'm so confused about the reason causing this problem, please help me out.
By the way, I find the size of synthia is 760*1280, and the height and width is set to 448, 640 in train_synthia in config.ini. 640 is the half of the 1280, but how we get the 448? Why not the 380, the half of the 760?

Thanks so much in advance!

**Comment by simonmeister** [comment]
First, the synthia resolution is 448 because it needs to be divisible by 2^6 = 64 (for the FlowNet architecture, we need all resolution components to be divisible by two 6 times). So instead of 1000, it should work if you choose the closest multiple of 64 instead (e.g. 1024 or 960).

**Comment by Blcony** [comment]
Thank you for your help~
I have figured it out~
