### ISSUE TITLE
ResourceExhaustedError - conv6

### ISSUE THREAD

**Issue by lenazherdeva** [simonmeister/UnFlow#32]
Hello! Thank you for work! 

But I have a question. I'm trying to run run.py with kitti dataset. But I got an error `ResourceExhaustedError (see above for traceback): OOM when allocating tensor of shape [1024] and type float
         [[Node: flownet_c/conv6/biases/Adam/Initializer/zeros = Const[_class=["loc:@flownet_c/conv6/biases"], dtype=DT_FLOAT, value=Tensor<type: float shape: [1024] values: 0 0 0...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]`.

Actually, I used 2 gpu GeForce GTX 108. I played with a batch_size, but nothing helped...

What can cause such a problem?

**Comment by simonmeister** [comment]
Hi! In general this means that you are out of GPU memory. Do you mean you are using the GTX 1080? How much GPU memory do you have and which batch size did you try? You could run nvidia-smi on the command line to check if something occupies your GPU memory first.

**Comment by lenazherdeva** [comment]
Yes, you're right! I've checked with nvidia-smi and some process occupied my memory. Now, it works! Thanks a lot!

**Comment by simonmeister** [comment]
Great! No problem :)
