### ISSUE TITLE
Why require an even number of frames?

### ISSUE THREAD

**Issue by clauslang** [simonmeister/UnFlow#33]
Hi,

Am I correct in the assumption, that both for training and for evaluation, an even number of input frames is required, and from these, non-overlapping pairs are built? I.e. if I have 10 input frames (im0, ..., im9) for evaluation, this will result in 5 image pairs for evaluation, ([im0, im1], [im2, im3], ...)?

If yes, why not increase the number of pairs by using all possible consecutive pairs ([im0, im1], [im1, im2], ...)? So e.g. with 10 input frames, there would be 9 pairs for evaluation.

Is this maybe specific to the data used? If I use my own data, any potential pitfalls in increasing the amount of data in this way?

cf. https://github.com/simonmeister/UnFlow/blob/master/src/e2eflow/core/input.py#L88

**Comment by simonmeister** [comment]
This helper is only used for test images or datasets which are not made up of consecutive frames. For e.g. kitti raw frames, the input_raw method is used, which constructs all possible consecutive pairs.

**Comment by clauslang** [comment]
Thank you for the clarification!
