### ISSUE TITLE
Please help, error! when run  python3 run.py --ex test

### ISSUE THREAD

**Issue by hbzhang** [simonmeister/UnFlow#35]
I have one GPU, I have configured config.in. What have I done wrong here?

/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/lib/bfloat16/bfloat16.h(466): error: no suitable constructor exists to convert from "float" to "tensorflow::bfloat16"

/usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/lib/bfloat16/bfloat16.h(467): error: no suitable constructor exists to convert from "float" to "tensorflow::bfloat16"

/usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/lib/bfloat16/bfloat16.h(468): error: no suitable constructor exists to convert from "float" to "tensorflow::bfloat16"

/usr/local/lib/python3.6/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(57): warning: integer conversion resulted in a change of sign

/usr/local/lib/python3.6/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(304): warning: integer conversion resulted in a change of sign

/usr/local/lib/python3.6/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(305): warning: integer conversion resulted in a change of sign

/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h(108): error: static assertion failed with "THIS_TYPE_IS_NOT_SUPPORTED"
          detected during:
            instantiation of "Scalar Eigen::internal::lgamma_impl<Scalar>::run(Scalar) [with Scalar=double]" 
(1517): here
            instantiation of "Eigen::internal::lgamma_retval<Eigen::internal::global_math_functions_filtering_base<Scalar, void>::type>::type Eigen::numext::lgamma(const Scalar &) [with Scalar=double]" 
/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/arch/CUDA/CudaSpecialFunctions.h(32): here

/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h(1015): error: static assertion failed with "THIS_TYPE_IS_NOT_SUPPORTED"
          detected during:
            instantiation of "Scalar Eigen::internal::polygamma_impl<Scalar>::run(Scalar, Scalar) [with Scalar=float]" 
(1535): here
            instantiation of "Eigen::internal::polygamma_retval<Eigen::internal::global_math_functions_filtering_base<Scalar, void>::type>::type Eigen::numext::polygamma(const Scalar &, const Scalar &) [with Scalar=float]" 
/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/arch/CUDA/CudaSpecialFunctions.h(67): here

/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h(1015): error: static assertion failed with "THIS_TYPE_IS_NOT_SUPPORTED"
          detected during:
            instantiation of "Scalar Eigen::internal::polygamma_impl<Scalar>::run(Scalar, Scalar) [with Scalar=double]" 
(1535): here
            instantiation of "Eigen::internal::polygamma_retval<Eigen::internal::global_math_functions_filtering_base<Scalar, void>::type>::type Eigen::numext::polygamma(const Scalar &, const Scalar &) [with Scalar=double]" 
/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/arch/CUDA/CudaSpecialFunctions.h(74): here

/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h(342): error: static assertion failed with "THIS_TYPE_IS_NOT_SUPPORTED"
          detected during:
            instantiation of "Scalar Eigen::internal::erf_impl<Scalar>::run(Scalar) [with Scalar=double]" 
(1541): here
            instantiation of "Eigen::internal::erf_retval<Eigen::internal::global_math_functions_filtering_base<Scalar, void>::type>::type Eigen::numext::erf(const Scalar &) [with Scalar=double]" 
/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/arch/CUDA/CudaSpecialFunctions.h(87): here

/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h(375): error: static assertion failed with "THIS_TYPE_IS_NOT_SUPPORTED"
          detected during:
            instantiation of "Scalar Eigen::internal::erfc_impl<Scalar>::run(Scalar) [with Scalar=float]" 
(1547): here
            instantiation of "Eigen::internal::erfc_retval<Eigen::internal::global_math_functions_filtering_base<Scalar, void>::type>::type Eigen::numext::erfc(const Scalar &) [with Scalar=float]" 
/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/arch/CUDA/CudaSpecialFunctions.h(94): here

/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h(375): error: static assertion failed with "THIS_TYPE_IS_NOT_SUPPORTED"
          detected during:
            instantiation of "Scalar Eigen::internal::erfc_impl<Scalar>::run(Scalar) [with Scalar=double]" 
(1547): here
            instantiation of "Eigen::internal::erfc_retval<Eigen::internal::global_math_functions_filtering_base<Scalar, void>::type>::type Eigen::numext::erfc(const Scalar &) [with Scalar=double]" 
/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/arch/CUDA/CudaSpecialFunctions.h(101): here

/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h(649): error: static assertion failed with "THIS_TYPE_IS_NOT_SUPPORTED"
          detected during:
            instantiation of "Scalar Eigen::internal::igamma_impl<Scalar>::run(Scalar, Scalar) [with Scalar=float]" 
(1553): here
            instantiation of "Eigen::internal::igamma_retval<Eigen::internal::global_math_functions_filtering_base<Scalar, void>::type>::type Eigen::numext::igamma(const Scalar &, const Scalar &) [with Scalar=float]" 
/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/arch/CUDA/CudaSpecialFunctions.h(110): here

/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h(649): error: static assertion failed with "THIS_TYPE_IS_NOT_SUPPORTED"
          detected during:
            instantiation of "Scalar Eigen::internal::igamma_impl<Scalar>::run(Scalar, Scalar) [with Scalar=double]" 
(1553): here
            instantiation of "Eigen::internal::igamma_retval<Eigen::internal::global_math_functions_filtering_base<Scalar, void>::type>::type Eigen::numext::igamma(const Scalar &, const Scalar &) [with Scalar=double]" 
/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/arch/CUDA/CudaSpecialFunctions.h(120): here

/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h(461): error: static assertion failed with "THIS_TYPE_IS_NOT_SUPPORTED"
          detected during:
            instantiation of "Scalar Eigen::internal::igammac_impl<Scalar>::run(Scalar, Scalar) [with Scalar=float]" 
(1559): here
            instantiation of "Eigen::internal::igammac_retval<Eigen::internal::global_math_functions_filtering_base<Scalar, void>::type>::type Eigen::numext::igammac(const Scalar &, const Scalar &) [with Scalar=float]" 
/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/arch/CUDA/CudaSpecialFunctions.h(128): here

/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h(461): error: static assertion failed with "THIS_TYPE_IS_NOT_SUPPORTED"
          detected during:
            instantiation of "Scalar Eigen::internal::igammac_impl<Scalar>::run(Scalar, Scalar) [with Scalar=double]" 
(1559): here
            instantiation of "Eigen::internal::igammac_retval<Eigen::internal::global_math_functions_filtering_base<Scalar, void>::type>::type Eigen::numext::igammac(const Scalar &, const Scalar &) [with Scalar=double]" 
/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/arch/CUDA/CudaSpecialFunctions.h(138): here

/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h(1064): error: static assertion failed with "THIS_TYPE_IS_NOT_SUPPORTED"
          detected during:
            instantiation of "Scalar Eigen::internal::betainc_impl<Scalar>::run(Scalar, Scalar, Scalar) [with Scalar=float]" 
(1565): here
            instantiation of "Eigen::internal::betainc_retval<Eigen::internal::global_math_functions_filtering_base<Scalar, void>::type>::type Eigen::numext::betainc(const Scalar &, const Scalar &, const Scalar &) [with Scalar=float]" 
/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/arch/CUDA/CudaSpecialFunctions.h(146): here

/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/SpecialFunctionsImpl.h(1064): error: static assertion failed with "THIS_TYPE_IS_NOT_SUPPORTED"
          detected during:
            instantiation of "Scalar Eigen::internal::betainc_impl<Scalar>::run(Scalar, Scalar, Scalar) [with Scalar=double]" 
(1565): here
            instantiation of "Eigen::internal::betainc_retval<Eigen::internal::global_math_functions_filtering_base<Scalar, void>::type>::type Eigen::numext::betainc(const Scalar &, const Scalar &, const Scalar &) [with Scalar=double]" 
/usr/local/lib/python3.6/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../src/SpecialFunctions/arch/CUDA/CudaSpecialFunctions.h(156): here

15 errors detected in the compilation of "/tmp/tmpxft_000013b5_00000000-6_backward_warp_op.cu.cpp1.ii".
Traceback (most recent call last):
  File "/home/cislab315/deeplearning/UnFlow/src/e2eflow/ops.py", line 61, in <module>
    op_lib = tf.load_op_library(lib_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./backward_warp_op.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 7, in <module>
    from e2eflow.core.train import Trainer
  File "/home/cislab315/deeplearning/UnFlow/src/e2eflow/core/train.py", line 12, in <module>
    from ..ops import forward_warp
  File "/home/cislab315/deeplearning/UnFlow/src/e2eflow/ops.py", line 63, in <module>
    compile(n)
  File "/home/cislab315/deeplearning/UnFlow/src/e2eflow/ops.py", line 45, in compile
    subprocess.check_output(nvcc_cmd, shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'nvcc -std=c++11 -c -o backward_warp_op.cu.o backward_warp_op.cu.cc -I/usr/local/lib/python3.6/dist-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0 -L/usr/local/lib/python3.6/dist-packages/tensorflow -ltensorflow_framework -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -I /usr/local --expt-relaxed-constexpr' returned non-zero exit status 1.

**Comment by hbzhang** [comment]
By the way, this is a fresh Ubuntu 17.10 os with CUDA 9.0 and tensorflow GPU 1.8.

**Comment by simonmeister** [comment]
You seem to have an issue with the compilation of custom ops, probably some library or tool that is not where the code expects it to be. Where is your cuda installation located?

**Comment by hbzhang** [comment]
Thanks @simonmeister, CUDA is located at 

/usr/local/cuda-9.0


I used pip install tensorflow-gpu

For CUDA 9.0, I used CUDA 9.0 runfile for installing 

https://developer.nvidia.com/cuda-90-download-archive

For CUDA driver i used 1080TI driver
NVIDIA-Linux-x86_64-384.130.run

What other information you need?

**Comment by simonmeister** [comment]
Does it have a symlink at /usr/local/cuda? You can also take a look at https://github.com/simonmeister/UnFlow/issues/23.

**Comment by hbzhang** [comment]
Yes, it has symlink.

**Comment by hbzhang** [comment]
By looking at #23, still can not solve the problem. I think custom OP causes a lot of trouble. May we consider using other alternatives rather than using custom OP? I think it might not be a long-term and maintainable solution.

**Comment by simonmeister** [comment]
I can't see any easy way to create the correlation op without custom C++ code. Additionally, the correlation layer is already the speed bottleneck for the network, so not using a dedicated op here would likely result in a significant slowdown of the complete network.

**Comment by hbzhang** [comment]
I think it can be a good idea to use customized code. But using some
wrapper to eliminate the strong dependency sounds more a
long-term solution.  I think yolo has done some good job in planning their
entire code structure....

**Comment by haichaoyu** [comment]
@simonmeister Just a piece of suggestion, it might be better to write the compilation code in shell scripts instead of Python. Here is a naive version. Hope it helps.

```
#!/bin/bash

# edit it
CUDA_ROOT="__CUDAROOT__"
# edit it if needed
LOCAL_INC="/home/__USER__/local"

CUDA_RT="$CUDA_ROOT/lib64"
NVCC="$CUDA_ROOT/bin/nvcc"

TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
TF_INC_NSYNC=$TF_INC/external/nsync/public
TF_LIB=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')

$NVCC -std=c++11 -c -o backward_warp_op.cu.o backward_warp_op.cu.cc -I$TF_INC -I$TF_INC_NSYNC -I$LOCAL_INC -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -L$TF_LIB -ltensorflow_framework --expt-relaxed-constexpr
g++ -std=c++11 -shared -o backward_warp_op.so backward_warp_op.cu.o backward_warp_op.cc -I$TF_INC -I$TF_INC_NSYNC -I$LOCAL_INC -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -L$CUDA_RT -lcudart -L$TF_LIB -ltensorflow_framework -O2 -D GOOGLE_CUDA=1

$NVCC -std=c++11 -c -o correlation_op.cu.o correlation_op.cu.cc -I$TF_INC -I$TF_INC_NSYNC -I$LOCAL_INC -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -L$TF_LIB -ltensorflow_framework --expt-relaxed-constexpr
g++ -std=c++11 -shared -o correlation_op.so correlation_op.cu.o correlation_op.cc -I$TF_INC -I$TF_INC_NSYNC -I$LOCAL_INC -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -L$CUDA_RT -lcudart -L$TF_LIB -ltensorflow_framework -O2 -D GOOGLE_CUDA=1

$NVCC -std=c++11 -c -o downsample_op.cu.o downsample_op.cu.cc -I$TF_INC -I$TF_INC_NSYNC -I$LOCAL_INC -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -L$TF_LIB -ltensorflow_framework --expt-relaxed-constexpr
g++ -std=c++11 -shared -o downsample_op.so downsample_op.cu.o downsample_op.cc -I$TF_INC -I$TF_INC_NSYNC -I$LOCAL_INC -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -L$CUDA_RT -lcudart -L$TF_LIB -ltensorflow_framework -O2 -D GOOGLE_CUDA=1

$NVCC -std=c++11 -c -o forward_warp_op.cu.o forward_warp_op.cu.cc -I$TF_INC -I$TF_INC_NSYNC -I$LOCAL_INC -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -L$TF_LIB -ltensorflow_framework --expt-relaxed-constexpr
g++ -std=c++11 -shared -o forward_warp_op.so forward_warp_op.cu.o forward_warp_op.cc -I$TF_INC -I$TF_INC_NSYNC -I$LOCAL_INC -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -L$CUDA_RT -lcudart -L$TF_LIB -ltensorflow_framework -O2 -D GOOGLE_CUDA=1

```

**Comment by simonmeister** [comment]
Thanks! I changed the code as suggested in the related issue https://github.com/simonmeister/UnFlow/issues/39. I hope it will work for most people this way.

**Comment by hbzhang** [comment]
Thanks!
