### ISSUE TITLE
Pyramidal Decomposition and Downsampling

### ISSUE THREAD

**Issue by gsaibro** [simonmeister/UnFlow#36]
Hi,
I found a little bug when trying to use smaller images with pyramidal cost function.

In unsupervised.py, we have this in the pyramidal loop:
`
im1_s = downsample(im1_s, 2)
im2_s = downsample(im2_s, 2)
mask_s = downsample(mask_s, 2)
`

But sometimes it's just not possible to do so (image size no divisible by 2). What I'm doing for now is just to limit the number of pyramidal images in Python, but I believe that a minimal modification in the C++ would be the proper solution.

Thanks.

**Comment by simonmeister** [comment]
One easy solution would be to directly replace downsample with tf.image.resize_area. It may be a bit slower (as it has no GPU implementation, as far as I know), but I actually didn't notice too much of a slowdown overall.

**Comment by simonmeister** [comment]
Fix merged (#53).
