### ISSUE TITLE
What would be the best way to do forward warping in the eval gui?

### ISSUE THREAD

**Issue by clauslang** [simonmeister/UnFlow#37]
Given two frames **Img1** and **Img2** and a flow **F**,  [eval_gui.py](https://github.com/simonmeister/UnFlow/blob/master/src/eval_gui.py) uses [image_warp.py](https://github.com/simonmeister/UnFlow/blob/master/src/e2eflow/core/image_warp.py) to do a backward warp on **Img2** with **F**, so that the user can compare the result to **Img1**. 

How can I achieve the opposite, i.e. forward warp **Img1** with **F** and compare the result to **Img2**? Conceptually, is forward warping with **F** equivalent to backward warping with **-F**? Or should I rather use the [custom ops](https://github.com/simonmeister/UnFlow/blob/master/ops/forward_warp_op.cc) defined for the network?

**Comment by simonmeister** [comment]
It's not equivalent - if you want to use backward warping to warp **Img1** towards **Img2** then you need the actual backward flow, not **-F** (but note that the inverse backward warping is not equivalent to forward warping). If a pixel that is visible in **Img1** becomes occluded in **Img2**, then the backward flow at the target pixel won't be **-F** of the original pixel, as a different object now determines the motion at the pixel. Unfortunately, I never finished the forward warping code. However, you can take a look at https://arxiv.org/abs/1711.05890v1, where they also use forward warping (for occlusion detection) and it seems to work very well.

**Comment by clauslang** [comment]
I've seen the other paper, too. Unfortunately, their code doesn't seem to be publicly available. So I'm trying to implement forward warping myself. I've got some conceptual questions:

- Assuming, the OF is integer-valued, what happens to pixels that are moving, but have no source pointing to them? As a very simple 1-dimensional example, if Im1 = [1, 2], and F = [1, 0], am I correct that that the warped image should just be [1, 1], basically copying the left pixel?
- In the float-valued case, let's say Im1 = [1, 2] again and F = [0.5, 0], should the result look like [0.5, 2.5], or would the values have to be added somehow in the bilinear interpolation?
- In both papers, for the calculation of the photometric loss, backward-warping is preferred over forward-warping. Is there any particular reason for this?

Thanks a lot for your help!

**Comment by simonmeister** [comment]
With backward warping, it is very easy to account for the error introduced by each specific flow vector prediction by using simple bilinear sampling. Forward warping is not so straightforward to achieve, and I am not sure if there is a definitive way to apply it to RGB images. I guess the other answers depend on what you want to achieve with forward warping. If you want to use it for occlusion detection, it would make more sense for the warped image to be [0,1] in your example, as in this case forward warping should identify pixels at which nothing is mapped. In the realistic float case, conceptually, you have a target density image defined as zero everywhere as a baseline first. Then, for each flow, you go to the pixels near the flow target position and add some density to each of them, e.g. by sampling from a 2D Gaussian centered at the actual flow target.
