### ISSUE TITLE
Out of date download URLs

### ISSUE THREAD

**Issue by djl11** [simonmeister/UnFlow#38]
Hi,

The URLs provided in the code for KITTI seemed to no longer work.
So I to updated data.py at line 82-84 with the following:

    KITTI_RAW_URL = 'https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data/'
    KITTI_2012_URL = 'https://s3.eu-central-1.amazonaws.com/avg-kitti/data_stereo_flow.zip'
    KITTI_2015_URL = 'https://s3.eu-central-1.amazonaws.com/avg-kitti/data_scene_flow.zip'

This is just a suggestion to update the code with the updated URLs.

**Comment by simonmeister** [comment]
Thanks! I updated it.
