### ISSUE TITLE
Incorporating occlusion-awareness into smoothness constraints

### ISSUE THREAD

**Issue by sahityamantravadi** [simonmeister/UnFlow#41]
Can I ask why occlusion-awareness is used in the data loss and consistency penalty, but not the smoothness constraints?

Is this something that would be useful for me to change if re-training?

Thanks!

**Comment by simonmeister** [comment]
Smoothness should in principle also hold inside regions becoming occluded. It may make sense to disable smoothness at motion boundaries, though.
