### ISSUE TITLE
An error of "gcc_cmd" which results in failure of building .so files

### ISSUE THREAD

**Issue by AnkaChan** [simonmeister/UnFlow#43]
https://github.com/simonmeister/UnFlow/blob/b98fafe38461fc43f9513e6fd4db9bb4e0ffbb8c/src/e2eflow/ops.py#L44

Missing the codes that replace the "{}" in gcc_cmd with meaningful configurations. This will make the g++ build fail to apply. 

I added such a sentence below:

> gcc_cmd = gcc_cmd.format("g++-4.9", " ".join([fn_so, fn_cu_o, fn_cc]), tf_inc, tf_lib)

And it worked out.

**Comment by simonmeister** [comment]
Thanks for noting that! I broke it in the last commit.
