### ISSUE TITLE
Where does the list in folder 'kitti_excludes' come from ? Especially the list of kitti2012, which can't be found on official website.

### ISSUE THREAD

**Issue by sunshinezhe** [simonmeister/UnFlow#49]
Hi Author,

I want to exclude the training and test sample of kitti2012 and kitti2015 from raw data just as you did.  However, I can't find the mapping list of kitti2012 on the official website. So, how do you get this mapping list.  
list of kitti2015 is found in 'devitkit' of kitti2015. However, list of kitti2012 isn't found in 'devikit' of kitti2012.

Thanks.

**Comment by simonmeister** [comment]
Hi, we did a brute force search for the training and test images in the full raw dataset.

**Comment by sunshinezhe** [comment]
> Hi, we did a brute force search for the training and test images in the full raw dataset.

Cool!!!

**Comment by hofingermarkus** [comment]
Hi, 
and thank you for providing the lists!

I am also interested in training on the raw data and therefore want to make sure that I don't have the test images in there. So I am curious why there are lists for Kitti2012 test+train and Kitti 2015 train but not for Kitti2015 test.
Is this data not present in the raw data or is there another reason why the list is not provided?
(I'm sorry if this question sounds silly, but I just want to make sure that I don't train on the test set....)

**Comment by hofingermarkus** [comment]
It seems as if there are 2 matches missing in your kitti_testing_2012 exclude list (found by matching MD5 checksums)

```
000194_10.png 2011_09_26/2011_09_26_drive_0086_sync/image_00/data/0000000130.png
000194_11.png 2011_09_26/2011_09_26_drive_0086_sync/image_00/data/0000000131.png
```
