### ISSUE TITLE
How to set up multiple GPU operations and how to modify the parameters of ‘’config.ini‘’,thank you

### ISSUE THREAD

**Issue by hyaihjq** [simonmeister/UnFlow#5]

**Comment by simonmeister** [comment]
To run with e.g. two GPUs (device id 0 and 1), you can set gpu_list=0,1 in config.ini. Note that the batch_size has to be divisible by two when using two GPUs, as it is split across them.

**Comment by hyaihjq** [comment]
thank you,your code is very good.
