### ISSUE TITLE
Implementation question about occlusion flag calculation

### ISSUE THREAD

**Issue by daigo0927** [simonmeister/UnFlow#50]
Hi, [@simonmeister](https://github.com/simonmeister).
Thanks for make your work publicly available.

Now, I have one question about the implementation of occlusion flag calculation in Eq.1 in the original paper. 
In this repository, the calculation is implemented as below,
```
mag_sq = length_sq(flow_fw) + length_sq(flow_bw)
```
but fllowing your paper, I think this operation should use warped flow, like
```
mag_sq_fw = length_sq(flow_fw) + length_sq(flow_bw_warped) 
# and
mag_sq_bw = length_sq(flow_bw) + length_sq(flow_fw_warped)
```
Is there any reason of the current implementation?, if so, I would appreciate if you tell me the reason.

Yours sincerely, 
Daigo Hirooka.

**Comment by simonmeister** [comment]
Yes, you are correct. This is a mistake in the current version of the code. I am not sure if it will make a noticable improvement in practice, but I have corrected it.

Thanks,
Simon

**Comment by xianshunw** [comment]
It seems that you haven't.
