### ISSUE TITLE
Evaluation results compared with the paper

### ISSUE THREAD

**Issue by jytime** [simonmeister/UnFlow#52]
Hi Simon,

I am testing the pre-trained models on the Kitti. In your paper (https://arxiv.org/pdf/1711.07837.pdf), the best unsupervised AEE (All) of UnFlow-C on Kitti 2015 training set is 8.80. But when testing, it returns:

> python eval_gui.py --variant=train_2015 --ex C 

> (C) EPE_noc = 3.185742938518524
> (C) EPE_all = 4.673751163482666
> (C) outliers_noc = 16.443058681488036
> (C) outliers_all = 21.893028831481935

 May I ask is this because you have improved the model? Thanks a lot.

**Comment by simonmeister** [comment]
In the eval_gui.py file, we have a default of

`tf.app.flags.DEFINE_integer('num', 10, 'Number of examples to evaluate. Set to -1 to evaluate all.')`.

Thus the numbers you report only give the errors over the first 10 examples from about 200. If you run 

`python eval_gui.py --variant=train_2015 --ex C --num -1`

 it should be equal to the results in the paper.

**Comment by jytime** [comment]
Thank you Simon
