### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by johannes-graeter** [simonmeister/UnFlow#54]
Hi Simon,

I tried to run the full and finetuned net on my Geforce GTX 980 with 4 GB memory and directly ran out of memory. What are the minimum hardware requirements for the net presented in the Paper (CSS-ft I guess :) )? (couldn't find it in there...) 

Best,

Johannes

**Comment by simonmeister** [comment]
We used a Titan X with 12GB, and if I remember correctly we also trained the non-stacked models on a 8GB GPU, however I no longer recall if we also could fit the stacked ones on these. You could also take a look at https://github.com/openai/gradient-checkpointing.

**Comment by johannes-graeter** [comment]
Worked like a charm (close to black magic ;) ) thx for the hint!
I can now train the full CSS net on a 4 GB graphics card and the speed loss is acceptable.

Have you thought about implementing LiteFlowNet (https://github.com/twhui/LiteFlowNet) with the unsupervised Unflow architecture?  For runtime speed that seems to be great! What are the limits?

**Comment by simonmeister** [comment]
Sorry, I am not familiar with the details of the paper. I skimmed it and it might be a good fit, but I don't have time to try this.
