### ISSUE TITLE
Pretrained Weights

### ISSUE THREAD

**Issue by dbarnes** [simonmeister/UnFlow#6]
Are any pretrained weights available to download from the paper to try the model without having to train?
Thanks

**Comment by simonmeister** [comment]
We have not uploaded them anywhere yet. I will try to do this in the next days!

**Comment by dbarnes** [comment]
Great, thanks

**Comment by simonmeister** [comment]
I uploaded them. Please have a look at the updated readme (section "Pre-trained models") for the download link and usage.

**Comment by dbarnes** [comment]
Thanks I will try them out.
