### ISSUE TITLE
Unsupervised training questions

### ISSUE THREAD

**Issue by ghost** [simonmeister/UnFlow#62]
Hi,

Many thanks for the code! I'm just a beginner of deep learning, and I may ask some very basic questions. I noticed that if I want to train your module in a pure unsupervised way with UnFlowCSS architecture, the first two networks C and CSS will be fixed.
1).  Is there any way I can train them all together and save the related network's checkpoints separately? 
2).  Is that going to turn down the module performance? 
3).  Also, I'm very curious about how you train the UnFlow-CSS. Did you train the UnFlow-C at first, and after it convergence, train the remain networks, like UnFlow-CS. I didn't find any details in the paper.

Cheers

**Comment by simonmeister** [comment]
Hi,

1) For supervised mode I think it should work if you use train_all=true (https://github.com/simonmeister/UnFlow/blob/master/config_template/config.ini#L63)
2) Possibly, and it may lead to overfitting more quickly and could make the training a bit less stable. If I remember correctly the FlowNet2 paper had some analysis regarding this and concluded that wasn't beneficial in their case.
3) Yes, we trained CSS in the same sequential way after training CS, including fixing all previous nets.

**Comment by ghost** [comment]
Many thanks for the reply, it is really helpful!
