### ISSUE TITLE
How flow vectors are stored and why do we need to do addition in this line of forward warping?

### ISSUE THREAD

**Issue by alisaaalehi** [simonmeister/UnFlow#65]
Hi @simonmeister ,

I was reading your forward_warp code and couldn't understand why you are doing addition in lines 29 and 30 instead of subtraction?

https://github.com/simonmeister/UnFlow/blob/ddb4bd32f762168ed38849f736b6a7d2094b0042/ops/forward_warp_op.cu.cc#L29
 
If you look at tensorflow's implementation of dense_image_warp, you can see that they are doing subtraction when it comes to finding query points for interpolation step.

https://github.com/tensorflow/tensorflow/blob/6612da89516247503f03ef76e974b51a434fb52e/tensorflow/contrib/image/python/ops/dense_image_warp.py#L210

I guess it all depends on how flow vectors are stored in flow matrixes. In the following picture, I have shown two different ways of storing a flow vector, which one do you think is correct one, Flow field 1 or Flow field 2? (I mean which one is standard, and used by benchmark datasets like Middlebury and Sintel?)

[ In this simple example one black dot moves from the location (2,6) in image one to (5,10) in image two. So, flow vector for that point is (3,4)]

![FlowExplained(1)](https://user-images.githubusercontent.com/39167815/55817762-d118ef80-5aba-11e9-840c-307a74c170cb.png)

If you make it clear that which one you are assuming, I can try to see why you are doing addition in those lines.

**Comment by simonmeister** [comment]
The dense_image_warp seems to be doing standard backward warping (which we also implemented in the backward warping C++ files or the image_warp script at https://github.com/simonmeister/UnFlow/blob/master/src/e2eflow/core/image_warp.py). Backward warp just does a bilinear sampling lookup using flow vectors. The forward warping code was actually not used in the paper and is incomplete. It's main use case would be for occlusion estimation. It's a bit more complicated than backward warping and also depends on the choice of the distribution you use as the target position.

**Comment by simonmeister** [comment]
Regarding the images you drew, flow field 2 is the (forward / standard) flow from image 1 to image 2. Flow field 1 makes sense if you want to express the inverse flow from image 2 to image 1, but then you would also have to have the value (-3, -4) instead of (3, 4).

**Comment by alisaaalehi** [comment]
Thank you @simonmeister  for your answer. Several points need to be considered. Before that, let be clear on terminology:
-  by **forward warping** I mean, given first image, second image and motion vectors from every pixel in the first image to the second image, we will warp the first image to get something close to the second image.
- by **backward warping**: given first image, second image and same flow vectors from every pixel in the first image to the second image, we want to warp the second image toward the first image and try to get something close to the first image. 

1- Are we on the same page about the definitions? If not, could you please make it more clear for me?
2 - What do you mean by:
>  ... depends on the choice of the distribution you use as the target position

Could you give me a reference or something to read more about it?

3- Actually, tensorflow is doing forward warping (trying to recover second image using first image and flow map), and strangely they are assuming that flow fields are stored in the first  format that I drow in the previous [post](https://github.com/simonmeister/UnFlow/issues/65#issue-431064498). You can see in the [description](https://github.com/tensorflow/tensorflow/blob/6612da89516247503f03ef76e974b51a434fb52e/tensorflow/contrib/image/python/ops/dense_image_warp.py#L172) of the function. I also wrote a simple Matlab code to confirm this.

4- You are saying that you didn't finish your forward_warp code, so we cannot discuss it further.

**Comment by alisaaalehi** [comment]
My simple Matlab code to do both forward and backward warping:

```matlab
function [frame_reconstructed] = warp_image(frame_a, frame_b, flow_mat, method)
% Warps frame a or frame b based on the method
% frame_a: first frame, gray scale image (eg. 250 X 300 X 1 matrix)
% frame_b: second frame, gray scale image (eg. 250 X 300 X 1 matrix)
% flow_mat: flow field, same size as images, 2 channels (eg. 250 X 300 X 2)

% Ali Salehi: alisaaalehi[at]gmail.com 
% Madhusudhanan Balasubramanian  mblsbrmn[at]memphis.edu 

    [m, n] = size(frame_a);

    % Form coordinate matrices for reconstruction
    [X, Y] = meshgrid(1 : n, 1 : m);  % Coordinates of locations
    
    if strcmp(method, 'forward')  % for clarity and simplicity, two separate sections
        X_new = X - flow_mat(:, :, 1);  % Corresponding x-coordinate in frame_b
        X_new(X_new < 1) = 1;  % handle boundries
        X_new(X_new > n) = n;
        %
        Y_new = Y - flow_mat(:, :, 2); % Corresponding y-coordinate in frame_b
        Y_new(Y_new < 1) = 1; % handle boundries
        Y_new(Y_new > m) = m;

        % Reconstruct frame b from frame a using the flow map
        frame_reconstructed = interp2(frame_a, X_new, Y_new, 'bicubic');
             
    elseif strcmp(method, 'backward')
        X_new = X + flow_mat(:, :, 1);  % Corresponding x-coordinate in frame a 
        X_new(X_new < 1) = 1; % handle boundries
        X_new(X_new > n) = n;
        %
        Y_new = Y + flow_mat(:, :, 2); % Corresponding y-coordinate in frame b
        Y_new(Y_new < 1) = 1; % handle boundries
        Y_new(Y_new > m) = m;

        % Reconstruct frame a from frame b using the flow map
        frame_reconstructed = interp2(frame_b, X_new, Y_new, 'bicubic');
    end
    
    % Fill NaNs with constant value 128
    nans = isnan(frame_reconstructed);
    frame_reconstructed(nans) = 128;
    
end


```

Test result on sample number 22711 from [FlyingChairs dataset](https://lmb.informatik.uni-freiburg.de/resources/datasets/FlyingChairs.en.html)

-  First frame
![img1](https://user-images.githubusercontent.com/39167815/56003536-70411100-5c8c-11e9-8818-311d696b684b.png)


-  Second frame
![img2](https://user-images.githubusercontent.com/39167815/56003555-98c90b00-5c8c-11e9-9df5-d56ce9823fa7.png)


-  Color coded flow
![color](https://user-images.githubusercontent.com/39167815/56003819-045fa800-5c8e-11e9-8f7f-7918b9ceec7a.png)


### Results
1. The result of **backward warping** using **my** Matlab code:
![backward-reconstructed](https://user-images.githubusercontent.com/39167815/56003601-d5950200-5c8c-11e9-80bc-178e2865111f.png)

2. The result of **forward warping** using **my** Matlab code:
![forward_reconstructed](https://user-images.githubusercontent.com/39167815/56003594-c746e600-5c8c-11e9-8b6f-bcfee91c356a.png)
3. The result of **warping** using **Tensorflow** function:
![0-warped](https://user-images.githubusercontent.com/39167815/56003650-1ee55180-5c8d-11e9-88bf-360541ad6e42.png)

As you can see from this example, Tensorflow function is doing forward warping. In this example, the result of backward warping makes more sense, because the flow vectors are stored in the second format (see previous posts or [this image](https://user-images.githubusercontent.com/39167815/55817762-d118ef80-5aba-11e9-840c-307a74c170cb.png) ) and this format can be easily used to do backward warping. Tensorflow doesn't give a reasonable result because it is doing forward warping and expecting the other format for flow field which is not in this case.

**Comment by simonmeister** [comment]
I think we're talking about two different things. Technically I'm used to the term forward warping as used e.g. here: https://www.cs.unc.edu/~lazebnik/research/fall08/lec08_faces.pdf - i.e. backward warping is always the method doing (bilinear) interpolation, forward warping needs to distribute the source intensity to the target by using some distribution. Forward warping from im1 to im2 is not the same as backward warping from im2 to im1 in the case of occlusion. This paper does something similar as we planned to do with the forward_warping code and may be useful to understand a bit more about the issue: https://arxiv.org/abs/1711.05890v1.

**Comment by alisaaalehi** [comment]
Thank you so much for the paper and the link, I will read them.

Another slightly different question to this topic:
Why did you define a new op for `backward_warp` in your code? I couldn't find a place in your code that function is used.
Isn't that `image_warp` function enough? Will tensorflow take care of gradients and backward pass for warping layer using that `image_warp` function?

**Comment by simonmeister** [comment]
I originally thought it may be faster than composing the op from the tensorflow primitives, but it turned out that it doesn't matter much, so the backward_warp code is not used anywhere.
