### ISSUE TITLE
Any template to train new dataset?

### ISSUE THREAD

**Issue by Kindpire** [simonmeister/UnFlow#68]
Hi,

Thanks for your paper! Do you have any template that I can easy to train the unsupervised model on my own dataset (such as folders of png images extracted from videos)?

Thanks!

**Comment by simonmeister** [comment]
Probably to late for OP. Just in case someone else finds this question in the future. You could just use the source/e2eflow/kitti for reference. The code is quite modular and you should be able to add a new dataset without much trouble. There are quite many different methods for loading datasets of different folder/file structures that are already implemented - you could just look through the datasets that already are supported and should be able to hack together a script that supports a new one easily.

**Comment by harikiran2995** [comment]
> Hi,
> 
> Thanks for your paper! Do you have any template that I can easy to train the unsupervised model on my own dataset (such as folders of png images extracted from videos)?
> 
> Thanks!

Are you able to train with your own dataset?
