### ISSUE TITLE
How to train with my downloaded data ?

### ISSUE THREAD

**Issue by RuiFeiHe** [simonmeister/UnFlow#70]
hello, I'm wondering if I can train with my downloaded dataset rather than to download the dataset at the folder again.
I'm hoping for your help.
BTW, can u tell me the number of parameters of your Unflow-CSS model ?

**Comment by simonmeister** [comment]
If I remember correctly, if the data is in place in the correct folder structure, it shouldn't be downloaded again. Sorry, don't know the parameters by heart.
