### ISSUE TITLE
Adapt custom ops to tf 1.5

### ISSUE THREAD

**Issue by simonmeister** [simonmeister/UnFlow#9]
Custom op compilation seems fixed in tf 1.5

**Comment by hnyz979** [comment]
Is tensorflow 1.4.1 OK with the op compilation?

**Comment by simonmeister** [comment]
There are still issues in tensorflow 1.5 that should be resolved before this can be supported in a clean way. https://github.com/tensorflow/tensorflow/issues/15002.

**Comment by hnyz979** [comment]
Thank you~ Actually the version issue took me a lot of time. I am now trying if this code can be modified to run with tensorflow1.4.1 and gcc 5.4. It really has taken a lot of time...

**Comment by simonmeister** [comment]
In the meantime, i would just use 1.2 - this should work without issues.

**Comment by Santana18** [comment]
The same question for Tensorflow 1.6 or 1.7?

**Comment by simonmeister** [comment]
I will check again if it works with 1.7 and update if possible.
